POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "qwer",
    "number": "1234"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "qwer"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "asdf",
    "number": "0000"
}